---
version: '3'

services:
        postgres:
                image: postgres
                environment:
                        POSTGRES_DB: boilerplate
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_USER: postgres
                hostname: postgres

        test:
                build: .
                command: "pytest test"
                ports:
                        - 5000:5000
                environment:
                        LOG_LEVEL: debug
                        ENV: test
                depends_on:
                        - postgres
        app:
                build: .
                ports:
                        - 5000:5000
                environment:
                        - LOG_LEVEL=debug
                        - app_name
                        - secret
                        - hash_algo
                        - db_host
                        - db_port
                        - db_user
                        - db_password
                        - db_database
                depends_on:
                        - postgres
